version: "3.8"

services:
  redis-scala:
    build: .
    volumes:
      - ./build.sbt:/app/build.sbt
      - ./project:/app/project
      - ./src:/app/src
      - ./your_program.sh:/app/your_program.sh
      - sbt-cache:/root/.sbt
      - ivy2-cache:/root/.ivy2
      - coursier-cache:/root/.cache/coursier
    working_dir: /app
    ports:
      - "6379:6379"
    stdin_open: true
    tty: true

volumes:
  sbt-cache:
  ivy2-cache:
  coursier-cache:
